diplay nama masjid from tetapan public api
Dev4w4n/e-masjid.my pull request #122
Opened 2024-03-09 18:39 UTC by naimhasim

#115

2024-03-09 21:19 UTC, rohaizanr commented
tak sesuai pakai API ni. esok saya akan explain kenapa...

https://github.com/Dev4w4n/e-masjid.my/issues/115#issuecomment-1986983267

2024-03-15 14:45 UTC, rohaizanr commented
pending API @fairul82

2024-03-30 14:11 UTC, rohaizanr commented
@naimhasim please re-sync main branch.

added public-web/src/service/Tetapan/TetapanMasjidApi.js

2024-03-30 15:19 UTC, rohaizanr requested changes

2024-03-30 15:19 UTC, rohaizanr commented on public-web/src/components/Home/Front.jsx
> +import { getTetapanNamaMasjid } from "../../service/Tetapan/TetapanMasjidApi";
salah merge ni

2024-03-30 16:29 UTC, naimhasim commented on public-web/src/components/Home/Front.jsx
> +import { getTetapanNamaMasjid } from "../../service/Tetapan/TetapanMasjidApi";
dah ok kot

2024-03-30 17:12 UTC, Dev4w4n commented
@naimhasim kena re-sync branch ... ada changes tadi

2024-03-30 17:52 UTC, rohaizanr approved these changes
perfect!
terima kasih

2024-03-30 17:53 UTC, merged