Tukar tarikh ke Tarikh Kutipan
Dev4w4n/e-masjid.my pull request #200
Opened 2024-04-04 16:48 UTC by nazhansukri11

1. Di page Tabung > Daftar , tukar label Tarikh ke Tarikh kutipan

2. Di page Tabung > Cetak, setelah edit tukar label Tarikh ke Tarikh kutipan

3. Di page Tabung > Cetak, setelah edit preload Tarikh ke Tarikh kutipan

4. Tarikh di Tabung > Cetak di tukar ke tarikh asal

2024-04-04 17:30 UTC, rohaizanr requested changes

2024-04-04 17:30 UTC, rohaizanr commented on dashboard/src/views/tabung/cetak/Cetak.js
> +          setStartDate(data.createDate)
kalau tak tukar tarikh .... ada ... "Kutipan tabung berjaya disimpan" .... tapi tak sae
kalau tukar tarikh ... takde "toast" tu ... tapi updated

2024-04-20 00:32 UTC, nazhansukri11 commented
Di page Tabung > Daftar , tukar label Tarikh ke Tarikh kutipan

Di page Tabung > Cetak, setelah edit tukar label Tarikh ke Tarikh kutipan

Di page Tabung > Cetak, setelah edit preload Tarikh ke Tarikh kutipan

Tarikh di Tabung > Cetak di tukar ke tarikh asal

Debug toast success d when success update data

2024-04-20 11:14 UTC, rohaizanr approved these changes
terima kasih

2024-04-20 11:15 UTC, merged