Update readme
Dev4w4n/e-masjid.my pull request #58
Opened 2024-01-10 17:02 UTC by rohaizanr

Ok tak ? @fazreil  @erosanwar

2024-01-10 22:55 UTC, fazreil approved these changes
Cun!

2024-01-11 13:40 UTC, erosanwar requested changes

2024-01-11 13:40 UTC, erosanwar commented on README.md
> +4. Ikut arahan seterusnya seperti dibawah bergantung kepada sistem pengoperasian komputer anda.
di bawah

2024-01-11 13:40 UTC, erosanwar commented on README.md
> +### (Linux)
tak perlu kurungan la rasanya

2024-01-11 13:40 UTC, erosanwar commented on README.md
> +### (Windows) - Gunakan terminal Git Bash di VSCode
ni pun tak perlu kurungan la

2024-01-11 13:40 UTC, erosanwar commented on README.md
> +1. *Fork* repo ini ke akaun github anda, contoh `https://github.com/<github-user>/e-masjid.my` , dengan menekan butang *Fork* di bahagian atas sebelah kanan laman web ini.
- akaun GitHub
- buang space sebelum koma

2024-01-11 13:40 UTC, erosanwar commented on README.md
> +3. Setelah selesai *Clone*, navigasi ke *Folder* e-masjid.my
- titik noktah hujung ayat
- *Clone* -> klon
- Folder -> folder

2024-01-11 13:40 UTC, erosanwar commented on README.en.md
> +1. Fork this repo to your personal github account, example `https://github.com/<github-user>/e-masjid.my`, by pressing the Fork button on the top right part of this page.
personal GitHub

2024-01-11 13:40 UTC, erosanwar commented on README.en.md
> +3. Once done, navigate to the e-masjid.my folder
titik noktah hujung ayat

2024-01-11 13:40 UTC, erosanwar commented on README.en.md
> +### (Linux)
buang kurungan

2024-01-11 13:40 UTC, erosanwar commented on README.en.md
> +### (Windows) - Use Git Bash terminal in VSCode
buang kurungan

2024-01-11 13:40 UTC, erosanwar commented on README.md
> +2. Setelah selesai *Fork*, *Clone* repo ini ke komputer anda.
*Clone* -> klon

2024-01-11 13:54 UTC, rohaizanr commented
@erosanwar updated

2024-01-11 13:56 UTC, erosanwar approved these changes

2024-01-11 14:00 UTC, rohaizanr commented
Terima kasih @fazreil @erosanwar

2024-01-11 14:00 UTC, merged