Handle network error when related microservice is down from public web and some validations for cadangan
Dev4w4n/e-masjid.my pull request #87
Opened 2024-01-25 04:02 UTC by pojicode

- handle network errors if related service is down dari perspective public web. For example public web up and other cadangan api and dashboard service down.
- add git ignore unruk intellij idea 
- add local profile (maven) untuk tabung api supaya boleh run tabung api independent locally
- add proxy ke http://localhost:3000 kat public web untuk avoid cors error 
- kat cadangan page handle email and phone validation incase if customer decide to enter email and phone, if empty we dont validate
- letak error message dalam constant file

2024-01-25 13:33 UTC, rohaizanr commented on public-web/src/constants/error.json
> +    "serviceDown": "Layanan kami sedang menghadapi gangguan. Sila cuba lagi kemudian",
Awat aku rasa lain mcm ja ayat ni @erosanwar any komen ?

2024-01-25 13:35 UTC, rohaizanr requested changes
mohon tengok balik

2024-01-25 13:38 UTC, erosanwar commented on public-web/src/constants/error.json
> +    "serviceDown": "Layanan kami sedang menghadapi gangguan. Sila cuba lagi kemudian",
Perkhidmatan?

2024-01-26 14:34 UTC, erosanwar requested changes

2024-01-26 14:34 UTC, erosanwar commented on public-web/src/constants/error.json
> +{
Tambah noktah kepada semua hujung ayat.

2024-01-26 14:34 UTC, erosanwar commented on api/tabung-api/pom.xml
> +		<profile>
Indentation lari.

2024-01-26 14:34 UTC, erosanwar commented on public-web/src/Pages/Cadangan.jsx
>        const nama = inputNama.current.value ? inputNama.current.value : null
Standardize end-of-line nak letak semicolon ke tidak.

2024-01-26 16:37 UTC, rohaizanr commented on public-web/src/Pages/Cadangan.jsx
>        const nama = inputNama.current.value ? inputNama.current.value : null
Betul jugak. Majority xdak semi colon

2024-01-27 06:07 UTC, pojicode commented on public-web/src/Pages/Cadangan.jsx
>        const nama = inputNama.current.value ? inputNama.current.value : null
dah tambah

2024-01-27 06:55 UTC, erosanwar approved these changes
LGTM

2024-01-27 11:29 UTC, Dev4w4n approved these changes
terima kasih

2024-01-27 11:30 UTC, merged